In [1]:
import pandas as pd
import sqlite3
from datetime import datetime, timedelta

In [40]:
conn = sqlite3.connect("./my_database.db")

addresses = pd.read_sql_query(
    "select * from address", conn,
    parse_dates=['created_at', 'updated_at']
)

contractors = pd.read_sql_query(
    "select * from contractors", conn,
    parse_dates=['created_at', 'updated_at']
)

invoices = pd.read_sql_query(
    "select * from invoice", conn,
    parse_dates=['invoice_date', 'created_at', 'updated_at']
)

line_items = pd.read_sql_query(
    "select * from line_item", conn,
    parse_dates=['created_at', 'updated_at']
)

tickets = pd.read_sql_query(
    "select * from ticket", conn,
    parse_dates=['assigned_at', 'completed_at', 'created_at', 'updated_at', 'start_time', 'due_date']
)

users = pd.read_sql_query(
    "select * from user", conn,
    parse_dates=['created_at', 'updated_at']
)

vendor_users = pd.read_sql_query(
    "select * from vendor_user", conn,
    parse_dates=['created_at', 'updated_at']
)

vendor_wells = pd.read_sql_query(
    "select * from vendor_well", conn,
    parse_dates=['created_at', 'updated_at']
)

vendors = pd.read_sql_query(
    "select * from vendor", conn,
    parse_dates=['created_at', 'updated_at']
)

well_locations = pd.read_sql_query(
    "select * from well_location", conn,
    parse_dates=['created_at', 'updated_at']
)

wells = pd.read_sql_query(
    "select * from well", conn,
    parse_dates=['created_at', 'updated_at']
)

work_orders = pd.read_sql_query(
    "select * from work_orders", conn,
    parse_dates=['created_at', 'updated_at']
)

contractor_performance = pd.read_sql_query(
    "select * from contractor_performance", conn,
    parse_dates=['created_at', 'updated_at']
)

In [3]:
# vendor_tickets = pd.merge(vendors, tickets, on='vendor_id', suffixes=['_vendor', '_ticket'])

In [4]:
# vendor_tickets.head()

In [5]:
tickets.head()

,ticket_id,work_order_id,description,assigned_contractor,priority,status,vendor_id,start_time,due_date,assigned_at,...,estimated_quantity,unit,special_requirements,anomaly_flag,anomaly_reason,created_at,updated_at,created_by,updated_by,additional_information
0,6f60ca89-3511-4315-8d9d-410c27af8863,9bd105bc-9d44-4d9d-b808-ee90701230bf,Item hear including inside. State side role am...,56068a7c-ad62-4721-b8b7-34fbb3e842db,routine,in progress,6b238ae3-e78c-431d-8797-565378b9f957,2025-11-10 11:38:26,2025-11-18 10:22:00,2025-11-07 22:33:51,...,93,hours,Long military simple my fund.,1,NaN,2025-11-07 08:20:42,2026-04-06 09:02:10.660820,a0d917bf-6567-4352-b10a-2250ea6779bf,79d770cd-bfe2-4fee-ad4b-277f0cd6a78a,"[{""name"": ""Kimberly Patterson"", ""residency"": ""..."
1,34263138-c399-4e55-ade9-ba5d39777bfe,d239e996-13c9-4f21-94e7-eb445d729cde,Pass support spend often ask. Office series si...,14ea3d7f-3b8e-4638-987e-8b4130c1433f,emergency,completed,6b238ae3-e78c-431d-8797-565378b9f957,2025-12-29 11:18:28,2026-01-03 04:49:31,2025-12-26 18:16:32,...,78,hours,Body sense paper commercial.,0,NaN,2025-12-26 13:16:03,2026-04-06 09:02:10.665995,aad6299d-f323-4363-b5e0-0b5ca3fe009f,acced291-2343-4e2e-a008-d51802b6ce17,"[{""name"": ""Brandon Villegas"", ""residency"": ""78..."
2,d13f40dd-b4ef-49fb-aab0-69640faedd28,8decdd26-3ab1-4dee-835f-496b5d8da716,Artist myself professional each. Strong their ...,82f16404-96cf-4087-a250-b68e73320f79,urgent,in progress,86baf51b-6894-4d12-8df8-e6860bb0d03b,2026-02-26 14:18:50,2026-03-01 20:40:22,2026-02-24 05:47:06,...,2,hours,Key trip charge look concern.,1,Performance stand no serious ten.,2026-02-22 19:02:58,2026-04-06 09:02:10.671979,4e9d4fe1-66d4-4987-ae30-4e39a7916277,6af456fb-9466-4613-903f-42ebcd2c6c8d,"[{""name"": ""Patricia Lara"", ""residency"": ""5324 ..."
3,4ac04553-6236-463d-9414-c0df0d3943d1,d62a8ecc-e515-41cf-ae69-c922053551c6,Kitchen teach get physical grow. Inside main t...,fb422951-1b45-43a7-b412-bbfcf0c9b585,routine,assigned,901ea53f-6ec4-4678-93f2-a9b71c9aa251,2025-10-22 18:38:29,2025-11-01 12:10:10,2025-10-22 07:38:13,...,93,hours,Gas six plant measure teacher.,1,Least talk card vote explain herself me newspa...,2025-10-21 06:39:24,2026-04-06 09:02:10.678402,95442c3b-6fdb-4d8a-8fc8-e37231195185,8144d497-5524-4a68-a6e3-5feb9eba862b,"[{""name"": ""Stacy Harris"", ""residency"": ""8827 J..."
4,10afc078-18c4-4808-acac-22593d91bfac,e6b4a9af-6251-4f49-9b4b-d68a3fc96f56,Ground idea prevent kind same speak clear feel...,25ed798e-0598-48a9-84a0-fc3fd653de88,routine,completed,e119bb7e-4302-41a0-80e9-ccab605f01a4,2026-03-26 07:08:18,2026-04-02 15:31:17,2026-03-24 03:27:20,...,4,hours,Reveal source dog old space.,0,NaN,2026-03-22 05:27:37,2026-04-06 09:02:10.684230,0c9592ae-d6d6-4167-a74e-a609983939d5,056d9e4b-59fd-4b58-b07b-b4fe41ad45a1,"[{""name"": ""James Taylor"", ""residency"": ""63359 ..."

In [6]:
# tickets['quarter'] = tickets['created_at'].dt.quarter

In [7]:
# completed_tickets = tickets[tickets['status'] == 'completed']
# completed_tickets.shape

In [8]:
# completed_tickets['completion_time'] = completed_tickets['completed_at'] - completed_tickets['assigned_at']

In [9]:
# completed_tickets['response_time'] = completed_tickets['start_time'] - completed_tickets['assigned_at']

In [10]:
# completed_tickets.groupby('quarter')['completion_time'].mean()

In [11]:
# completed_tickets.groupby('quarter')['response_time'].mean()

In [12]:
# completed_tickets.groupby('quarter')['ticket_id'].count()

In [13]:
# tickets['month'] = tickets['created_at'].dt.month_name()

In [14]:
# tickets[tickets['quarter'] == 4].month.value_counts()

In [15]:
# completed_tickets.groupby('vendor_id')['completion_time'].mean().sort_values(ascending=False)

In [16]:
# completed_tickets.groupby('vendor_id')['response_time'].mean().sort_values(ascending=False)

In [17]:
# completed_tickets.groupby('vendor_id')['ticket_id'].count()

In [18]:
# vendor_kpis = completed_tickets.groupby('vendor_id').agg({
#     "completion_time": 'mean',
#     "response_time": 'mean',
#     "ticket_id": 'count'
# })
# vendor_kpis

In [19]:
# vendor_info = vendors[['vendor_id', 'company_name']]

In [20]:
# vendor_info

In [21]:
# pd.merge(vendor_info, vendor_kpis, on='vendor_id')

# Vendor/Client Admin KPIs

## On Time Delivery %
percentage of tickets completed on time within a specified range

In [22]:
cols = ['ticket_id', 'created_at', 'assigned_at', 'start_time', 'completed_at', 'due_date']

In [23]:
def overall_vendor_on_time_delivery(start_time, end_time=datetime.now()):
    df = tickets[tickets['created_at'].between(start_time, end_time)]
    completed_late = df['completed_at'] > df['due_date']
    overdue = (df['completed_at'].isna()) & (df['due_date'] < end_time)

    df['on_time'] = ~(completed_late | overdue)

    ticket_kpi = df.groupby('vendor_id').agg({
        'on_time': 'mean',
        'ticket_id': 'count'
    })
    ticket_kpi['on_time'] = (ticket_kpi['on_time'] * 100).round(2)
    vendor_info = vendors[['vendor_id', 'company_name']]

    vendor_kpi = pd.merge(vendor_info, ticket_kpi, on='vendor_id')
    return vendor_kpi

In [24]:
# three_months = pd.Timestamp.now() - pd.DateOffset(months=3)
# tickets_created_3_months = tickets[tickets['created_at'] >= three_months].reset_index()

# completed_late = tickets_created_3_months['completed_at'] > tickets_created_3_months['due_date']
# overdue = (tickets_created_3_months['completed_at'].isna()) & (tickets_created_3_months['due_date'] < pd.Timestamp.now())

# tickets_created_3_months['on_time'] = ~(completed_late | overdue)

# # tickets_created_3_months[cols].head(10)

# tickets_created_3_months['on_time'].value_counts(normalize=True)

# # tickets_created_3_months[tickets_created_3_months['on_time'] == True][cols]

# tickets_created_3_months.groupby('vendor_id')['on_time'].mean().round(4) * 100

In [25]:
nov_2025 = datetime.strptime('2025-11-01', '%Y-%m-%d')
feb_2026 = datetime.strptime('2026-03-01', '%Y-%m-%d')

In [26]:
overall_vendor_on_time_delivery(nov_2025, feb_2026)

,vendor_id,company_name,on_time,ticket_id
0,3c0d000d-535b-4008-bf4a-7d351976d8cd,"Allen, Gonzales and Perry",33.52,179
1,82620a2e-5be4-4549-8231-dc6041c08bc1,Herring-Gregory,36.75,166
2,e119bb7e-4302-41a0-80e9-ccab605f01a4,"Knapp, Bennett and Harris",37.19,199
3,02111fdf-c201-498e-8611-c28cc9134bb2,"Coleman, Krause and Hernandez",40.22,184
4,427b642e-0d19-4162-9c34-7be0c4a1e090,Pratt-Arroyo,41.67,120
5,86baf51b-6894-4d12-8df8-e6860bb0d03b,Williams PLC,43.65,126
6,aa5ed799-6294-4d7d-b874-e4ed7566cb25,"Jackson, Riley and Hawkins",39.63,164
7,0a721f79-bc66-405d-abf1-8ce93f45302e,Smith-Nguyen,37.77,188
8,6b238ae3-e78c-431d-8797-565378b9f957,"Conrad, Smith and Gomez",40.23,174
9,901ea53f-6ec4-4678-93f2-a9b71c9aa251,Simpson-Odonnell,43.10,174

In [27]:
overall_vendor_on_time_delivery(nov_2025)

,vendor_id,company_name,on_time,ticket_id
0,3c0d000d-535b-4008-bf4a-7d351976d8cd,"Allen, Gonzales and Perry",31.62,234
1,82620a2e-5be4-4549-8231-dc6041c08bc1,Herring-Gregory,34.58,214
2,e119bb7e-4302-41a0-80e9-ccab605f01a4,"Knapp, Bennett and Harris",35.71,252
3,02111fdf-c201-498e-8611-c28cc9134bb2,"Coleman, Krause and Hernandez",39.00,241
4,427b642e-0d19-4162-9c34-7be0c4a1e090,Pratt-Arroyo,39.61,154
5,86baf51b-6894-4d12-8df8-e6860bb0d03b,Williams PLC,40.37,161
6,aa5ed799-6294-4d7d-b874-e4ed7566cb25,"Jackson, Riley and Hawkins",39.32,206
7,0a721f79-bc66-405d-abf1-8ce93f45302e,Smith-Nguyen,37.34,241
8,6b238ae3-e78c-431d-8797-565378b9f957,"Conrad, Smith and Gomez",40.34,233
9,901ea53f-6ec4-4678-93f2-a9b71c9aa251,Simpson-Odonnell,39.47,228

In [28]:
(tickets['completed_at'].dt.normalize() == datetime.today().date()).sum()

np.int64(0)

In [29]:
tickets['completed_at'].dt.normalize().value_counts()

completed_at
2025-07-23    11
2025-12-10    11
2025-08-01    10
2026-03-22    10
2026-01-04    10
              ..
2025-09-10     1
2025-05-08     1
2025-04-08     1
2026-02-05     1
2025-05-01     1
Name: count, Length: 364, dtype: int64

## Average Duration of Ticket

In [30]:
df = tickets[~tickets['completed_at'].isna()]
df.shape

(1683, 25)

In [31]:
df['completion_time'] = df['completed_at'] - df['assigned_at']

In [32]:
df['completion_time'].mean()

Timedelta('1 days 17:50:57.926322')

In [33]:
def overall_vendor_ticket_duration(start_time, end_time=datetime.now()):
    df = tickets[tickets['completed_at'].between(start_time, end_time)] # all completed tickets in time range
    df['completion_time'] = df['completed_at'] - df['assigned_at']

    kpi = df.groupby('vendor_id')['completion_time'].mean().sort_values(ascending=True)
    vendor_info = vendors[['vendor_id', 'company_name']]

    vendor_kpi = pd.merge(vendor_info, kpi, on='vendor_id')

    return vendor_kpi

In [34]:
overall_vendor_ticket_duration(nov_2025, feb_2026)

,vendor_id,company_name,completion_time
0,3c0d000d-535b-4008-bf4a-7d351976d8cd,"Allen, Gonzales and Perry",1 days 23:52:25.549019
1,82620a2e-5be4-4549-8231-dc6041c08bc1,Herring-Gregory,1 days 17:51:36.061224
2,e119bb7e-4302-41a0-80e9-ccab605f01a4,"Knapp, Bennett and Harris",1 days 14:29:32.683333
3,02111fdf-c201-498e-8611-c28cc9134bb2,"Coleman, Krause and Hernandez",1 days 21:01:45.970149
4,427b642e-0d19-4162-9c34-7be0c4a1e090,Pratt-Arroyo,1 days 17:21:39.978723
5,86baf51b-6894-4d12-8df8-e6860bb0d03b,Williams PLC,1 days 18:59:34.311111
6,aa5ed799-6294-4d7d-b874-e4ed7566cb25,"Jackson, Riley and Hawkins",1 days 12:54:36.839285
7,0a721f79-bc66-405d-abf1-8ce93f45302e,Smith-Nguyen,1 days 16:24:06.295081
8,6b238ae3-e78c-431d-8797-565378b9f957,"Conrad, Smith and Gomez",1 days 15:39:29.475409
9,901ea53f-6ec4-4678-93f2-a9b71c9aa251,Simpson-Odonnell,1 days 22:29:32.824561

In [35]:
overall_vendor_ticket_duration(nov_2025)

,vendor_id,company_name,completion_time
0,3c0d000d-535b-4008-bf4a-7d351976d8cd,"Allen, Gonzales and Perry",1 days 21:57:04.897058
1,82620a2e-5be4-4549-8231-dc6041c08bc1,Herring-Gregory,1 days 19:55:06.370967
2,e119bb7e-4302-41a0-80e9-ccab605f01a4,"Knapp, Bennett and Harris",1 days 17:35:02.038961
3,02111fdf-c201-498e-8611-c28cc9134bb2,"Coleman, Krause and Hernandez",1 days 20:10:56.022727
4,427b642e-0d19-4162-9c34-7be0c4a1e090,Pratt-Arroyo,1 days 18:15:31.214285
5,86baf51b-6894-4d12-8df8-e6860bb0d03b,Williams PLC,1 days 16:48:33.783333
6,aa5ed799-6294-4d7d-b874-e4ed7566cb25,"Jackson, Riley and Hawkins",1 days 14:04:04.300000
7,0a721f79-bc66-405d-abf1-8ce93f45302e,Smith-Nguyen,1 days 15:34:36.651162
8,6b238ae3-e78c-431d-8797-565378b9f957,"Conrad, Smith and Gomez",1 days 15:26:05.654761
9,901ea53f-6ec4-4678-93f2-a9b71c9aa251,Simpson-Odonnell,1 days 23:44:09.089743

## Currently Open Tickets

In [36]:
def overall_vendor_open_tickets():
    open_tickets = tickets[tickets['status'] != 'completed']
    kpi = pd.pivot_table(open_tickets, index='vendor_id', columns='status', values='ticket_id', aggfunc='count').reset_index()
    kpi['total'] = kpi['assigned'] + kpi['in progress']
    vendor_info = vendors[['vendor_id', 'company_name']]

    vendor_kpi = pd.merge(vendor_info, kpi, on='vendor_id')
    return vendor_kpi

In [37]:
overall_vendor_open_tickets()

,vendor_id,company_name,assigned,in progress,total
0,3c0d000d-535b-4008-bf4a-7d351976d8cd,"Allen, Gonzales and Perry",192,165,357
1,82620a2e-5be4-4549-8231-dc6041c08bc1,Herring-Gregory,168,159,327
2,e119bb7e-4302-41a0-80e9-ccab605f01a4,"Knapp, Bennett and Harris",176,224,400
3,02111fdf-c201-498e-8611-c28cc9134bb2,"Coleman, Krause and Hernandez",199,187,386
4,427b642e-0d19-4162-9c34-7be0c4a1e090,Pratt-Arroyo,137,100,237
5,86baf51b-6894-4d12-8df8-e6860bb0d03b,Williams PLC,127,112,239
6,aa5ed799-6294-4d7d-b874-e4ed7566cb25,"Jackson, Riley and Hawkins",150,161,311
7,0a721f79-bc66-405d-abf1-8ce93f45302e,Smith-Nguyen,172,170,342
8,6b238ae3-e78c-431d-8797-565378b9f957,"Conrad, Smith and Gomez",207,193,400
9,901ea53f-6ec4-4678-93f2-a9b71c9aa251,Simpson-Odonnell,153,165,318

## Average Rating Per Vendor

In [51]:
def overall_vendor_performance():
    vendor_contractor = pd.merge(vendors, contractors, on='vendor_id')
    vc_performance = pd.merge(vendor_contractor, contractor_performance, on='contractor_id')
    return vc_performance.groupby('company_name')['rating'].mean().round(2).sort_values(ascending=False)

In [52]:
overall_vendor_performance()

company_name
Williams PLC                     3.27
Jackson, Riley and Hawkins       3.10
Simpson-Odonnell                 3.05
Conrad, Smith and Gomez          3.00
Knapp, Bennett and Harris        2.99
Allen, Gonzales and Perry        2.98
Coleman, Krause and Hernandez    2.98
Herring-Gregory                  2.98
Pratt-Arroyo                     2.97
Smith-Nguyen                     2.95
Name: rating, dtype: float64

In [61]:
def overall_vendor_performance_2():
    vendor_contractor_performance = pd.read_sql_query(
        """
        select v.company_name, round(cp.avg_rating, 2) as rating
        from (
            select c.vendor_id, avg(cp.rating) as avg_rating
            from contractor_performance cp
            join contractors c using (contractor_id)
            group by c.vendor_id
        ) cp
        join vendor v using (vendor_id)
        order by cp.avg_rating desc;
        """, conn
    )
    # print(vendor_contractor_performance.head())
    return vendor_contractor_performance.groupby('company_name')['rating'].mean().round(2).sort_values(ascending=False)

In [62]:
overall_vendor_performance_2()

company_name
Williams PLC                     3.27
Jackson, Riley and Hawkins       3.10
Simpson-Odonnell                 3.05
Conrad, Smith and Gomez          3.00
Knapp, Bennett and Harris        2.99
Allen, Gonzales and Perry        2.98
Coleman, Krause and Hernandez    2.98
Herring-Gregory                  2.98
Pratt-Arroyo                     2.97
Smith-Nguyen                     2.95
Name: rating, dtype: float64

In [63]:
%timeit overall_vendor_performance()

24.6 ms ± 1.07 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [64]:
%timeit overall_vendor_performance_2()

6.59 ms ± 501 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)